### ISSUE TITLE
User can create a profile

### ISSUE THREAD

**Issue by Johnny-Baltazar** [Johnny-Baltazar/final-project#1]
## ⚙️ Feature description: 
> ##### What capability will users have when this feature is merged?

User can create a profile.
## 📐 Functionality
Users will be able to register a profile with user information of a username, first name, last name, email address, their location, password, and details about their self (optional).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screenshot 2022-10-18 205949](https://user-images.githubusercontent.com/25161542/196594700-be13ee61-c05c-4dbf-8caf-bf21c1bd716f.png)
![Screenshot 2022-10-18 210112](https://user-images.githubusercontent.com/25161542/196594745-0fd0ba73-6d40-4a04-a682-95163438a214.png)
![Screenshot 2022-10-18 214044](https://user-images.githubusercontent.com/25161542/196599304-d4aa322b-cbc5-403a-8614-2f89ba35f889.png)
![Screenshot 2022-10-18 214105](https://user-images.githubusercontent.com/25161542/196599321-efe77be2-d0e9-4c71-9f31-4c16044a3bd3.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to `CREATE TABLE` `public.users`.
  - [x] `public.users` table to include `userId`, `userName`, `firstName`, `lastName`, `email`, `password`, `location`, and `details`.
- [x] Update `data.sql` to `insert` into `users`, `userId`, `userName`, `firstName`, `lastName`, `email`, `hashedPassword`, `location`, and `details`.
  - [x] Insert values `$1`, `anonymous`, `$3`, `$4`, `$5`, `$argon2i$v=19$m=4096,t=3,p=1$h7icQD/xZr8akZsX+hNA0A$h68atJWyjvunAwNOpSpMfg9sPvoMQ6dKwoh0dJhurWA`, `$7`, `$8`.

### ☁️ Server Tasks

- [x] Update `server/index.js` to send a post request for a user to sign-up to create a profile.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Set up hash routing for sign-up path.
- [x] Create a component for a `NavBar`.
  - [x] Ensure that the `hash` `route` is updated to `sign-in` when `login` is clicked. 
  - [x] Ensure that the `RegForm` is hidden when `Login` is clicked on the `NavBar`. 
- [x] Create a component for a `PageContainer`.
- [x] Create a component to open an `AppDrawer`.
  - [x] Ensure that the `hash` `route` is updated when an option is clicked. 
  - [x] Ensure that the `AppDrawer` closed when the arrow is clicked. 
- [x] Create a `RegForm` component so a user can create a profile.
  - [x] Make sure that the `user` properties can be saved to the database. 
- [x] Create a component to `Redirect`.  
- [x] Create an `AppContext` component. 
- [x] Create a `parseRoute` component.
- [x] Create an `AuthPage` component.

### 🧑‍⚕️ Clean Up Tasks
- [x]  Ensure the Details `textarea` is not required.
- [x] Add styling to the `navbar`.
- [x] Add styling for the `registration` `form`.
- [x] Ensure the `register` form is centered on the page.
- [x] Add styling to the `AppDrawer`.
- [ ] Make sure that the app looks good in mobile and desktop views.
- [ ] Make sure that a `user` can create a profile from the webpage. 
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
